const lenderArr = [
  {
    userProfile: {
      firstName: "Soraya",
      lastName: "McCune",
      secondaryEmailAddress: "sg.dmullon@gmail.com",
      workNumber: 0,
      nameOfCompanylastName: "",
      phoneNumber: 8054718368,
      companyPhoneNumber: 0,
      fax: 0,
      companyStreetAddress: "",
      zip: 0,
      personalNotes: "",
      sourceName: "",
      sourcePhone: "0",
      sourceEmail: "",
      clientPaysBrokerDemand: false,
      lenderPaysRebates: false,
      brokerPaidThroughEscrow: false,
      lenderNameBank: false,
      lenderNameCDFI: false,
      lenderNameCreditUnion: false,
      lenderNameInsuranceCompany: false,
      lenderNameNonBankLender: false,
      lenderNamePrivateEquity: false
    },
    ownerOccupied: {
      purchase: "YES",
      refinance: "UNKNOWN",
      cashOutRefinance: "UNKNOWN",
      renovationImprovement: "UNKNOWN",
      bridge: "UNKNOWN",
      revolvingBusinessLOC1stPosition: "UNKNOWN",
      revolvingBusinessLOC2stPosition: "UNKNOWN",
      ownerMinumumLoanAmount: 0,
      ownerMaximumLoanAmount: 0,
      ownerMaxLTVPercent: 0,
      ownerMinDCR: 0
    },
    investmentNonSBARealEstate: {
      investmentPurchase: "UNKNOWN",
      investmentRefinance: "UNKNOWN",
      investmentCashOutRefinance: "UNKNOWN",
      investmentRenovationImprovement: "UNKNOWN",
      investmentBridge: "UNKNOWN",
      investmentRevolvingBusinessLOC1stPosition: "UNKNOWN",
      investmentRevolvingBusinessLOC2stPosition: "UNKNOWN",
      investmentNonSBAMinumumLoanAmount: 0,
      investmentNonSBAMaximumLoanAmount: 0,
      investmentNonSBAMaxLTVPercent: 0,
      investmentNonSBAMaxLTCPercent: 0,
      investmentNonSBAMaxARV: 0,
      investmentNonSBAMinDebtYield: 0,
      investmentNonSBAMinDCR: 0
    },
    sbaSevenALoans: {
      sbaExpress: "UNKNOWN",
      exoprtExpressWC: "UNKNOWN",
      internationalTrade: "UNKNOWN",
      seasonalCAPLines: "UNKNOWN",
      ownerOccupiedCommercial: "UNKNOWN",
      debtRefinance: "UNKNOWN",
      contractCAPLines: "UNKNOWN",
      buildersCAPLines: "UNKNOWN",
      workingCAPLines: "UNKNOWN",
      sbaMicroLoan: "UNKNOWN",
      businessAcquisition: "UNKNOWN",
      SBASevenMinumumLoanAmount: 0,
      SBASevenMaximumLoanAmount: 0,
      SBASevenMaxLTVPercent: 0,
      SBASevenMinDCR: 0
    },
    SBAFiveFourLoans: {
      SBAFiveFourFirstDeedRealEstate: "UNKNOWN",
      SBAFiveFourFirstDeedRealEquipment: "UNKNOWN",
      SBAFiveFourRefinanceProgram: "UNKNOWN",
      SBAFiveFourFirstDeedRealEstateBridge: "UNKNOWN",
      SBAFiveFourFirstDeedEquipmentBridge: "UNKNOWN",
      SBAFiveFourRefinanceBridge: "UNKNOWN",
      SBAFiveFourMinumumLoanAmount: 0,
      SBAFiveFourMaximumLoanAmount: 0,
      SBAFiveFourMaxLTVPercent: 0,
      SBAFiveFourMinDCR: 0
    },
    construction: {
      investment: "UNKNOWN",
      renovation: "UNKNOWN",
      residentialLongterm: "UNKNOWN",
      residentialFixandFlip: "UNKNOWN",
      groundUpSpecHome: "UNKNOWN",
      ownerUser: "UNKNOWN",
      tractHomes: "UNKNOWN",
      apartments: "UNKNOWN",
      constructiontoPermanent: "UNKNOWN",
      landDevelopment: "UNKNOWN",
      residential: "UNKNOWN",
      PUD: "UNKNOWN",
      purchaseWithLand: "UNKNOWN",
      entitlements: "UNKNOWN",
      miniperm: "UNKNOWN",
      leasedLand: "UNKNOWN",
      brokenProject: "UNKNOWN",
      manufacturedHomeSingleWide: "UNKNOWN",
      manufacturedHomeDoubleWide: "UNKNOWN",
      constructionMinumumLoanAmount: 0,
      constructionMaximumLoanAmount: 0,
      constructionMaxLTVPercent: 0,
      constructionMaxLTCPercent: 0,
      constructionNonSBAMaxARV: 0,
      constructionMinDCR: 0
    },
    businessLendingNonSBA: {
      businessCreditCard: "UNKNOWN",
      businessExpansionnoRE: "UNKNOWN",
      equipmentFinancing: "UNKNOWN",
      businessAcquisitionsMergers: "UNKNOWN",
      franchisePurchases: "UNKNOWN",
      revolvingBLOCFirstPosition: "UNKNOWN",
      revolvingBLOCSecondPosition: "UNKNOWN",
      accountsReceivable: "UNKNOWN",
      crossCollateral: "UNKNOWN",
      equipment: "UNKNOWN",
      invoiceFinancing: "UNKNOWN",
      irrevocableTrust: "UNKNOWN",
      projectionBased: "UNKNOWN",
      purchaseOrderFinancing: "UNKNOWN",
      realEstate: "UNKNOWN",
      stockSavings: "UNKNOWN",
      businessLendingMinumumLoanAmount: 0,
      businessLendingMaximumLoanAmount: 0,
      businessLendingMaxLTVPercent: 0,
      businessLendingMinDCR: 0
    },
    nonCommercialResidentialLending: {
      conventionalFNMA: "UNKNOWN",
      governmentFHA: "UNKNOWN",
      kRehab: "UNKNOWN",
      portfolio: "UNKNOWN",
      jumbo: "UNKNOWN"
    },
    privateMoneyLending: {
      privateMoneyMinumumLoanAmount: 0,
      privateMoneyMaximumLoanAmount: 0,
      privateMoneyMaxLTVPercentCommercial: 0,
      privateMoneyMaxLTVPercentResidential: 0,
      privateMoneyMaxARVCommercial: 0,
      privateMoneyMaxARVResidential: 0,
      privateMoneyMinimumDCR: 0,
      privateMoneyFixedRateAmortized: "UNKNOWN",
      privateMoneyAdjustableRateAmortized: "UNKNOWN",
      privateMoneyinterestOnly: "UNKNOWN",
      privateMoneyInterestRateMin: 0,
      privateMoneyInterestRateMax: 0,
      privateMoneyTermRangeMax: 0,
      privateMoneyTermRangeMin: 0,
      privateMoneyFeesFlatMin: 0,
      privateMoneyFeesFlatMax: 0,
      privateMoneyFeesPointsMin: 0,
      privateMoneyFeesPointsMax: 0,
      privateClosingCostsMin: 0,
      privateClosingCostsMax: 0,
      privateDaysToFundingMin: 0,
      privateDaysToFundingMax: 0
    },
    multiUnitLiving: {
      multiUnitFraternitySorority: "UNKNOWN",
      multiUnitMultiFamily: "UNKNOWN",
      multiUnitStudentHousing: "UNKNOWN",
      multiUnitHotelMotelFlag: "UNKNOWN",
      multiUnitMobileHomePark: "UNKNOWN",
      multiUnitCondoTownHome: "UNKNOWN",
      multiUnitHotelMotelNoFlag: "UNKNOWN",
      multiUnitAssisstedLiving: "UNKNOWN"
    },
    automotive: {
      automotiveBodyShop: "UNKNOWN",
      automotiveDealerShip: "UNKNOWN",
      automotiveCarWash: "UNKNOWN",
      automotiveGasStation: "UNKNOWN"
    },
    healthcare: {
      healthcareDoctorsOffice: "UNKNOWN",
      healthcareHospital: "UNKNOWN",
      healthcareMedicalLab: "UNKNOWN"
    },
    retail: {
      retailRestaurant: "UNKNOWN",
      retailMall: "UNKNOWN",
      retailSingleTenant: "UNKNOWN"
    },
    miscellaneous: {
      miscellaneousChurchReligion: "UNKNOWN",
      miscellaneousIndustrialWarehouse: "UNKNOWN",
      miscellaneousOffice: "UNKNOWN",
      miscellaneousEntertainment: "UNKNOWN",
      miscellaneousMaritimeMarina: "UNKNOWN",
      miscellaneousRawLand: "UNKNOWN",
      miscellaneousFarmAgriculture: "UNKNOWN",
      miscellaneousMixedUse: "UNKNOWN",
      miscellaneousStorage: "UNKNOWN",
      miscellaneousLeaseholdProperty: "UNKNOWN"
    },
    financialCreditIssue: {
      financialCreditIssueBankruptcy: "UNKNOWN",
      financialCreditIssueNonUSCitizen: "UNKNOWN",
      financialCreditIssueMissedPayments: "UNKNOWN",
      financialCreditIssueForeclosure: "UNKNOWN",
      financialCreditIssueShortSale: "UNKNOWN",
      financialCreditIssueTaxLiens: "UNKNOWN",
      financialCreditIssueLowFICO: "UNKNOWN",
      financialCreditIssueLowLiquidity: "UNKNOWN",
      financialCreditIssueJudgements: "UNKNOWN"
    },
    miscellaneousQualifiers: {
      miscellaneousQualifiersExchange: "UNKNOWN",
      miscellaneousQualifiersNonProfit: "UNKNOWN",
      miscellaneousQualifiersNonRecourse: "UNKNOWN",
      miscellaneousQualifiersFactoring: "UNKNOWN",
      miscellaneousQualifiersCannabisRelated: "UNKNOWN",
      miscellaneousQualifiersStartUp: "UNKNOWN",
      miscellaneousQualifiersAssestBasedLending: "UNKNOWN",
      miscellaneousQualifiersResidentialBridge: "UNKNOWN",
      miscellaneousQualifiersInterestOnlyIndefinite: "UNKNOWN",
      miscellaneousQualifiersInterestOnlyIntoTerm: "UNKNOWN",
      miscellaneousQualifiersRelationshipPricing: "UNKNOWN",
      miscellaneousQualifiersRequiredDepositRelationship: "UNKNOWN",
      miscellaneousQualifiersFirstLienPosition: "UNKNOWN",
      miscellaneousQualifiersSecondLientPosition: "UNKNOWN",
      miscellaneousQualifiersSubordinateFinancing: "UNKNOWN"
    },
    avatar: "/static/images/profile-image.jpg",
    following: [],
    followers: [],
    username: "soraya",
    email: "scm1116@gmail.com",
    password: "$2b$10$2icPz8YI0O2SgGi5Lw.hNuiVJdVsAqypisi2qk1kx4WX2jBZGkoAC"
  },
  {
    userProfile: {
      firstName: "",
      lastName: "",
      secondaryEmailAddress: "",
      workNumber: 0,
      nameOfCompanylastName: "",
      phoneNumber: 0,
      companyPhoneNumber: 0,
      fax: 0,
      companyStreetAddress: "",
      zip: 0,
      personalNotes: "",
      sourceName: "",
      sourcePhone: "0",
      sourceEmail: "",
      clientPaysBrokerDemand: false,
      lenderPaysRebates: false,
      brokerPaidThroughEscrow: false,
      lenderNameBank: false,
      lenderNameCDFI: false,
      lenderNameCreditUnion: false,
      lenderNameInsuranceCompany: false,
      lenderNameNonBankLender: false,
      lenderNamePrivateEquity: false
    },
    ownerOccupied: {
      purchase: "YES",
      refinance: "UNKNOWN",
      cashOutRefinance: "UNKNOWN",
      renovationImprovement: "UNKNOWN",
      bridge: "UNKNOWN",
      revolvingBusinessLOC1stPosition: "UNKNOWN",
      revolvingBusinessLOC2stPosition: "UNKNOWN",
      ownerMinumumLoanAmount: 0,
      ownerMaximumLoanAmount: 0,
      ownerMaxLTVPercent: 0,
      ownerMinDCR: 0
    },
    investmentNonSBARealEstate: {
      investmentPurchase: "UNKNOWN",
      investmentRefinance: "UNKNOWN",
      investmentCashOutRefinance: "UNKNOWN",
      investmentRenovationImprovement: "UNKNOWN",
      investmentBridge: "UNKNOWN",
      investmentRevolvingBusinessLOC1stPosition: "UNKNOWN",
      investmentRevolvingBusinessLOC2stPosition: "UNKNOWN",
      investmentNonSBAMinumumLoanAmount: 0,
      investmentNonSBAMaximumLoanAmount: 0,
      investmentNonSBAMaxLTVPercent: 0,
      investmentNonSBAMaxLTCPercent: 0,
      investmentNonSBAMaxARV: 0,
      investmentNonSBAMinDebtYield: 0,
      investmentNonSBAMinDCR: 0
    },
    sbaSevenALoans: {
      sbaExpress: "UNKNOWN",
      exoprtExpressWC: "UNKNOWN",
      internationalTrade: "UNKNOWN",
      seasonalCAPLines: "UNKNOWN",
      ownerOccupiedCommercial: "UNKNOWN",
      debtRefinance: "UNKNOWN",
      contractCAPLines: "UNKNOWN",
      buildersCAPLines: "UNKNOWN",
      workingCAPLines: "UNKNOWN",
      sbaMicroLoan: "UNKNOWN",
      businessAcquisition: "UNKNOWN",
      SBASevenMinumumLoanAmount: 0,
      SBASevenMaximumLoanAmount: 0,
      SBASevenMaxLTVPercent: 0,
      SBASevenMinDCR: 0
    },
    SBAFiveFourLoans: {
      SBAFiveFourFirstDeedRealEstate: "UNKNOWN",
      SBAFiveFourFirstDeedRealEquipment: "UNKNOWN",
      SBAFiveFourRefinanceProgram: "UNKNOWN",
      SBAFiveFourFirstDeedRealEstateBridge: "UNKNOWN",
      SBAFiveFourFirstDeedEquipmentBridge: "UNKNOWN",
      SBAFiveFourRefinanceBridge: "UNKNOWN",
      SBAFiveFourMinumumLoanAmount: 0,
      SBAFiveFourMaximumLoanAmount: 0,
      SBAFiveFourMaxLTVPercent: 0,
      SBAFiveFourMinDCR: 0
    },
    construction: {
      investment: "UNKNOWN",
      renovation: "UNKNOWN",
      residentialLongterm: "UNKNOWN",
      residentialFixandFlip: "UNKNOWN",
      groundUpSpecHome: "UNKNOWN",
      ownerUser: "UNKNOWN",
      tractHomes: "UNKNOWN",
      apartments: "UNKNOWN",
      constructiontoPermanent: "UNKNOWN",
      landDevelopment: "UNKNOWN",
      residential: "UNKNOWN",
      PUD: "UNKNOWN",
      purchaseWithLand: "UNKNOWN",
      entitlements: "UNKNOWN",
      miniperm: "UNKNOWN",
      leasedLand: "UNKNOWN",
      brokenProject: "UNKNOWN",
      manufacturedHomeSingleWide: "UNKNOWN",
      manufacturedHomeDoubleWide: "UNKNOWN",
      constructionMinumumLoanAmount: 0,
      constructionMaximumLoanAmount: 0,
      constructionMaxLTVPercent: 0,
      constructionMaxLTCPercent: 0,
      constructionNonSBAMaxARV: 0,
      constructionMinDCR: 0
    },
    businessLendingNonSBA: {
      businessCreditCard: "UNKNOWN",
      businessExpansionnoRE: "UNKNOWN",
      equipmentFinancing: "UNKNOWN",
      businessAcquisitionsMergers: "UNKNOWN",
      franchisePurchases: "UNKNOWN",
      revolvingBLOCFirstPosition: "UNKNOWN",
      revolvingBLOCSecondPosition: "UNKNOWN",
      accountsReceivable: "UNKNOWN",
      crossCollateral: "UNKNOWN",
      equipment: "UNKNOWN",
      invoiceFinancing: "UNKNOWN",
      irrevocableTrust: "UNKNOWN",
      projectionBased: "UNKNOWN",
      purchaseOrderFinancing: "UNKNOWN",
      realEstate: "UNKNOWN",
      stockSavings: "UNKNOWN",
      businessLendingMinumumLoanAmount: 0,
      businessLendingMaximumLoanAmount: 0,
      businessLendingMaxLTVPercent: 0,
      businessLendingMinDCR: 0
    },
    nonCommercialResidentialLending: {
      conventionalFNMA: "UNKNOWN",
      governmentFHA: "UNKNOWN",
      kRehab: "UNKNOWN",
      portfolio: "UNKNOWN",
      jumbo: "UNKNOWN"
    },
    privateMoneyLending: {
      privateMoneyMinumumLoanAmount: 0,
      privateMoneyMaximumLoanAmount: 0,
      privateMoneyMaxLTVPercentCommercial: 0,
      privateMoneyMaxLTVPercentResidential: 0,
      privateMoneyMaxARVCommercial: 0,
      privateMoneyMaxARVResidential: 0,
      privateMoneyMinimumDCR: 0,
      privateMoneyFixedRateAmortized: "UNKNOWN",
      privateMoneyAdjustableRateAmortized: "UNKNOWN",
      privateMoneyinterestOnly: "UNKNOWN",
      privateMoneyInterestRateMin: 0,
      privateMoneyInterestRateMax: 0,
      privateMoneyTermRangeMax: 0,
      privateMoneyTermRangeMin: 0,
      privateMoneyFeesFlatMin: 0,
      privateMoneyFeesFlatMax: 0,
      privateMoneyFeesPointsMin: 0,
      privateMoneyFeesPointsMax: 0,
      privateClosingCostsMin: 0,
      privateClosingCostsMax: 0,
      privateDaysToFundingMin: 0,
      privateDaysToFundingMax: 0
    },
    multiUnitLiving: {
      multiUnitFraternitySorority: "UNKNOWN",
      multiUnitMultiFamily: "UNKNOWN",
      multiUnitStudentHousing: "UNKNOWN",
      multiUnitHotelMotelFlag: "UNKNOWN",
      multiUnitMobileHomePark: "UNKNOWN",
      multiUnitCondoTownHome: "UNKNOWN",
      multiUnitHotelMotelNoFlag: "UNKNOWN",
      multiUnitAssisstedLiving: "UNKNOWN"
    },
    automotive: {
      automotiveBodyShop: "UNKNOWN",
      automotiveDealerShip: "UNKNOWN",
      automotiveCarWash: "UNKNOWN",
      automotiveGasStation: "UNKNOWN"
    },
    healthcare: {
      healthcareDoctorsOffice: "UNKNOWN",
      healthcareHospital: "UNKNOWN",
      healthcareMedicalLab: "UNKNOWN"
    },
    retail: {
      retailRestaurant: "UNKNOWN",
      retailMall: "UNKNOWN",
      retailSingleTenant: "UNKNOWN"
    },
    miscellaneous: {
      miscellaneousChurchReligion: "UNKNOWN",
      miscellaneousIndustrialWarehouse: "UNKNOWN",
      miscellaneousOffice: "UNKNOWN",
      miscellaneousEntertainment: "UNKNOWN",
      miscellaneousMaritimeMarina: "UNKNOWN",
      miscellaneousRawLand: "UNKNOWN",
      miscellaneousFarmAgriculture: "UNKNOWN",
      miscellaneousMixedUse: "UNKNOWN",
      miscellaneousStorage: "UNKNOWN",
      miscellaneousLeaseholdProperty: "UNKNOWN"
    },
    financialCreditIssue: {
      financialCreditIssueBankruptcy: "UNKNOWN",
      financialCreditIssueNonUSCitizen: "UNKNOWN",
      financialCreditIssueMissedPayments: "UNKNOWN",
      financialCreditIssueForeclosure: "UNKNOWN",
      financialCreditIssueShortSale: "UNKNOWN",
      financialCreditIssueTaxLiens: "UNKNOWN",
      financialCreditIssueLowFICO: "UNKNOWN",
      financialCreditIssueLowLiquidity: "UNKNOWN",
      financialCreditIssueJudgements: "UNKNOWN"
    },
    miscellaneousQualifiers: {
      miscellaneousQualifiersExchange: "UNKNOWN",
      miscellaneousQualifiersNonProfit: "UNKNOWN",
      miscellaneousQualifiersNonRecourse: "UNKNOWN",
      miscellaneousQualifiersFactoring: "UNKNOWN",
      miscellaneousQualifiersCannabisRelated: "UNKNOWN",
      miscellaneousQualifiersStartUp: "UNKNOWN",
      miscellaneousQualifiersAssestBasedLending: "UNKNOWN",
      miscellaneousQualifiersResidentialBridge: "UNKNOWN",
      miscellaneousQualifiersInterestOnlyIndefinite: "UNKNOWN",
      miscellaneousQualifiersInterestOnlyIntoTerm: "UNKNOWN",
      miscellaneousQualifiersRelationshipPricing: "UNKNOWN",
      miscellaneousQualifiersRequiredDepositRelationship: "UNKNOWN",
      miscellaneousQualifiersFirstLienPosition: "UNKNOWN",
      miscellaneousQualifiersSecondLientPosition: "UNKNOWN",
      miscellaneousQualifiersSubordinateFinancing: "UNKNOWN"
    },
    avatar: "/static/images/profile-image.jpg",
    following: [],
    followers: [],
    username: "esharp",
    email: "esharpdesigns@me.com",
    password: "$2b$10$PF.hLgADfETnN/kPW34LeeolA1BChjVROD8kJLjUfTFJz/Y0Ws2r."
  },
  {
    userProfile: {
      firstName: "",
      lastName: "",
      secondaryEmailAddress: "",
      workNumber: 0,
      nameOfCompanylastName: "",
      phoneNumber: 0,
      companyPhoneNumber: 0,
      fax: 0,
      companyStreetAddress: "",
      zip: 0,
      personalNotes: "",
      sourceName: "",
      sourcePhone: "0",
      sourceEmail: "",
      clientPaysBrokerDemand: false,
      lenderPaysRebates: false,
      brokerPaidThroughEscrow: false,
      lenderNameBank: false,
      lenderNameCDFI: false,
      lenderNameCreditUnion: false,
      lenderNameInsuranceCompany: false,
      lenderNameNonBankLender: false,
      lenderNamePrivateEquity: false
    },
    ownerOccupied: {
      purchase: "YES",
      refinance: "UNKNOWN",
      cashOutRefinance: "UNKNOWN",
      renovationImprovement: "UNKNOWN",
      bridge: "UNKNOWN",
      revolvingBusinessLOC1stPosition: "UNKNOWN",
      revolvingBusinessLOC2stPosition: "UNKNOWN",
      ownerMinumumLoanAmount: 0,
      ownerMaximumLoanAmount: 0,
      ownerMaxLTVPercent: 0,
      ownerMinDCR: 0
    },
    investmentNonSBARealEstate: {
      investmentPurchase: "UNKNOWN",
      investmentRefinance: "UNKNOWN",
      investmentCashOutRefinance: "UNKNOWN",
      investmentRenovationImprovement: "UNKNOWN",
      investmentBridge: "UNKNOWN",
      investmentRevolvingBusinessLOC1stPosition: "UNKNOWN",
      investmentRevolvingBusinessLOC2stPosition: "UNKNOWN",
      investmentNonSBAMinumumLoanAmount: 0,
      investmentNonSBAMaximumLoanAmount: 0,
      investmentNonSBAMaxLTVPercent: 0,
      investmentNonSBAMaxLTCPercent: 0,
      investmentNonSBAMaxARV: 0,
      investmentNonSBAMinDebtYield: 0,
      investmentNonSBAMinDCR: 0
    },
    sbaSevenALoans: {
      sbaExpress: "UNKNOWN",
      exoprtExpressWC: "UNKNOWN",
      internationalTrade: "UNKNOWN",
      seasonalCAPLines: "UNKNOWN",
      ownerOccupiedCommercial: "UNKNOWN",
      debtRefinance: "UNKNOWN",
      contractCAPLines: "UNKNOWN",
      buildersCAPLines: "UNKNOWN",
      workingCAPLines: "UNKNOWN",
      sbaMicroLoan: "UNKNOWN",
      businessAcquisition: "UNKNOWN",
      SBASevenMinumumLoanAmount: 0,
      SBASevenMaximumLoanAmount: 0,
      SBASevenMaxLTVPercent: 0,
      SBASevenMinDCR: 0
    },
    SBAFiveFourLoans: {
      SBAFiveFourFirstDeedRealEstate: "UNKNOWN",
      SBAFiveFourFirstDeedRealEquipment: "UNKNOWN",
      SBAFiveFourRefinanceProgram: "UNKNOWN",
      SBAFiveFourFirstDeedRealEstateBridge: "UNKNOWN",
      SBAFiveFourFirstDeedEquipmentBridge: "UNKNOWN",
      SBAFiveFourRefinanceBridge: "UNKNOWN",
      SBAFiveFourMinumumLoanAmount: 0,
      SBAFiveFourMaximumLoanAmount: 0,
      SBAFiveFourMaxLTVPercent: 0,
      SBAFiveFourMinDCR: 0
    },
    construction: {
      investment: "UNKNOWN",
      renovation: "UNKNOWN",
      residentialLongterm: "UNKNOWN",
      residentialFixandFlip: "UNKNOWN",
      groundUpSpecHome: "UNKNOWN",
      ownerUser: "UNKNOWN",
      tractHomes: "UNKNOWN",
      apartments: "UNKNOWN",
      constructiontoPermanent: "UNKNOWN",
      landDevelopment: "UNKNOWN",
      residential: "UNKNOWN",
      PUD: "UNKNOWN",
      purchaseWithLand: "UNKNOWN",
      entitlements: "UNKNOWN",
      miniperm: "UNKNOWN",
      leasedLand: "UNKNOWN",
      brokenProject: "UNKNOWN",
      manufacturedHomeSingleWide: "UNKNOWN",
      manufacturedHomeDoubleWide: "UNKNOWN",
      constructionMinumumLoanAmount: 0,
      constructionMaximumLoanAmount: 0,
      constructionMaxLTVPercent: 0,
      constructionMaxLTCPercent: 0,
      constructionNonSBAMaxARV: 0,
      constructionMinDCR: 0
    },
    businessLendingNonSBA: {
      businessCreditCard: "UNKNOWN",
      businessExpansionnoRE: "UNKNOWN",
      equipmentFinancing: "UNKNOWN",
      businessAcquisitionsMergers: "UNKNOWN",
      franchisePurchases: "UNKNOWN",
      revolvingBLOCFirstPosition: "UNKNOWN",
      revolvingBLOCSecondPosition: "UNKNOWN",
      accountsReceivable: "UNKNOWN",
      crossCollateral: "UNKNOWN",
      equipment: "UNKNOWN",
      invoiceFinancing: "UNKNOWN",
      irrevocableTrust: "UNKNOWN",
      projectionBased: "UNKNOWN",
      purchaseOrderFinancing: "UNKNOWN",
      realEstate: "UNKNOWN",
      stockSavings: "UNKNOWN",
      businessLendingMinumumLoanAmount: 0,
      businessLendingMaximumLoanAmount: 0,
      businessLendingMaxLTVPercent: 0,
      businessLendingMinDCR: 0
    },
    nonCommercialResidentialLending: {
      conventionalFNMA: "UNKNOWN",
      governmentFHA: "UNKNOWN",
      kRehab: "UNKNOWN",
      portfolio: "UNKNOWN",
      jumbo: "UNKNOWN"
    },
    privateMoneyLending: {
      privateMoneyMinumumLoanAmount: 0,
      privateMoneyMaximumLoanAmount: 0,
      privateMoneyMaxLTVPercentCommercial: 0,
      privateMoneyMaxLTVPercentResidential: 0,
      privateMoneyMaxARVCommercial: 0,
      privateMoneyMaxARVResidential: 0,
      privateMoneyMinimumDCR: 0,
      privateMoneyFixedRateAmortized: "UNKNOWN",
      privateMoneyAdjustableRateAmortized: "UNKNOWN",
      privateMoneyinterestOnly: "UNKNOWN",
      privateMoneyInterestRateMin: 0,
      privateMoneyInterestRateMax: 0,
      privateMoneyTermRangeMax: 0,
      privateMoneyTermRangeMin: 0,
      privateMoneyFeesFlatMin: 0,
      privateMoneyFeesFlatMax: 0,
      privateMoneyFeesPointsMin: 0,
      privateMoneyFeesPointsMax: 0,
      privateClosingCostsMin: 0,
      privateClosingCostsMax: 0,
      privateDaysToFundingMin: 0,
      privateDaysToFundingMax: 0
    },
    multiUnitLiving: {
      multiUnitFraternitySorority: "UNKNOWN",
      multiUnitMultiFamily: "UNKNOWN",
      multiUnitStudentHousing: "UNKNOWN",
      multiUnitHotelMotelFlag: "UNKNOWN",
      multiUnitMobileHomePark: "UNKNOWN",
      multiUnitCondoTownHome: "UNKNOWN",
      multiUnitHotelMotelNoFlag: "UNKNOWN",
      multiUnitAssisstedLiving: "UNKNOWN"
    },
    automotive: {
      automotiveBodyShop: "UNKNOWN",
      automotiveDealerShip: "UNKNOWN",
      automotiveCarWash: "UNKNOWN",
      automotiveGasStation: "UNKNOWN"
    },
    healthcare: {
      healthcareDoctorsOffice: "UNKNOWN",
      healthcareHospital: "UNKNOWN",
      healthcareMedicalLab: "UNKNOWN"
    },
    retail: {
      retailRestaurant: "UNKNOWN",
      retailMall: "UNKNOWN",
      retailSingleTenant: "UNKNOWN"
    },
    miscellaneous: {
      miscellaneousChurchReligion: "UNKNOWN",
      miscellaneousIndustrialWarehouse: "UNKNOWN",
      miscellaneousOffice: "UNKNOWN",
      miscellaneousEntertainment: "UNKNOWN",
      miscellaneousMaritimeMarina: "UNKNOWN",
      miscellaneousRawLand: "UNKNOWN",
      miscellaneousFarmAgriculture: "UNKNOWN",
      miscellaneousMixedUse: "UNKNOWN",
      miscellaneousStorage: "UNKNOWN",
      miscellaneousLeaseholdProperty: "UNKNOWN"
    },
    financialCreditIssue: {
      financialCreditIssueBankruptcy: "UNKNOWN",
      financialCreditIssueNonUSCitizen: "UNKNOWN",
      financialCreditIssueMissedPayments: "UNKNOWN",
      financialCreditIssueForeclosure: "UNKNOWN",
      financialCreditIssueShortSale: "UNKNOWN",
      financialCreditIssueTaxLiens: "UNKNOWN",
      financialCreditIssueLowFICO: "UNKNOWN",
      financialCreditIssueLowLiquidity: "UNKNOWN",
      financialCreditIssueJudgements: "UNKNOWN"
    },
    miscellaneousQualifiers: {
      miscellaneousQualifiersExchange: "UNKNOWN",
      miscellaneousQualifiersNonProfit: "UNKNOWN",
      miscellaneousQualifiersNonRecourse: "UNKNOWN",
      miscellaneousQualifiersFactoring: "UNKNOWN",
      miscellaneousQualifiersCannabisRelated: "UNKNOWN",
      miscellaneousQualifiersStartUp: "UNKNOWN",
      miscellaneousQualifiersAssestBasedLending: "UNKNOWN",
      miscellaneousQualifiersResidentialBridge: "UNKNOWN",
      miscellaneousQualifiersInterestOnlyIndefinite: "UNKNOWN",
      miscellaneousQualifiersInterestOnlyIntoTerm: "UNKNOWN",
      miscellaneousQualifiersRelationshipPricing: "UNKNOWN",
      miscellaneousQualifiersRequiredDepositRelationship: "UNKNOWN",
      miscellaneousQualifiersFirstLienPosition: "UNKNOWN",
      miscellaneousQualifiersSecondLientPosition: "UNKNOWN",
      miscellaneousQualifiersSubordinateFinancing: "UNKNOWN"
    },
    avatar: "/static/images/profile-image.jpg",
    following: [],
    followers: [],
    username: "gdoming",
    email: "greg.domingue1@gmail.com",
    password: "$2b$10$yjstSPl4e2eyqwKbjwPflu79RJRUmijXsGLPqhzoOZPnPoc7/3p2y"
  },
  {
    userProfile: {
      firstName: "",
      lastName: "",
      secondaryEmailAddress: "",
      workNumber: 0,
      nameOfCompanylastName: "",
      phoneNumber: 0,
      companyPhoneNumber: 0,
      fax: 0,
      companyStreetAddress: "",
      zip: 0,
      personalNotes: "",
      sourceName: "",
      sourcePhone: "0",
      sourceEmail: "",
      clientPaysBrokerDemand: false,
      lenderPaysRebates: false,
      brokerPaidThroughEscrow: false,
      lenderNameBank: false,
      lenderNameCDFI: false,
      lenderNameCreditUnion: false,
      lenderNameInsuranceCompany: false,
      lenderNameNonBankLender: false,
      lenderNamePrivateEquity: false
    },
    ownerOccupied: {
      purchase: "YES",
      refinance: "UNKNOWN",
      cashOutRefinance: "UNKNOWN",
      renovationImprovement: "UNKNOWN",
      bridge: "UNKNOWN",
      revolvingBusinessLOC1stPosition: "UNKNOWN",
      revolvingBusinessLOC2stPosition: "UNKNOWN",
      ownerMinumumLoanAmount: 0,
      ownerMaximumLoanAmount: 0,
      ownerMaxLTVPercent: 0,
      ownerMinDCR: 0
    },
    investmentNonSBARealEstate: {
      investmentPurchase: "UNKNOWN",
      investmentRefinance: "UNKNOWN",
      investmentCashOutRefinance: "UNKNOWN",
      investmentRenovationImprovement: "UNKNOWN",
      investmentBridge: "UNKNOWN",
      investmentRevolvingBusinessLOC1stPosition: "UNKNOWN",
      investmentRevolvingBusinessLOC2stPosition: "UNKNOWN",
      investmentNonSBAMinumumLoanAmount: 0,
      investmentNonSBAMaximumLoanAmount: 0,
      investmentNonSBAMaxLTVPercent: 0,
      investmentNonSBAMaxLTCPercent: 0,
      investmentNonSBAMaxARV: 0,
      investmentNonSBAMinDebtYield: 0,
      investmentNonSBAMinDCR: 0
    },
    sbaSevenALoans: {
      sbaExpress: "UNKNOWN",
      exoprtExpressWC: "UNKNOWN",
      internationalTrade: "UNKNOWN",
      seasonalCAPLines: "UNKNOWN",
      ownerOccupiedCommercial: "UNKNOWN",
      debtRefinance: "UNKNOWN",
      contractCAPLines: "UNKNOWN",
      buildersCAPLines: "UNKNOWN",
      workingCAPLines: "UNKNOWN",
      sbaMicroLoan: "UNKNOWN",
      businessAcquisition: "UNKNOWN",
      SBASevenMinumumLoanAmount: 0,
      SBASevenMaximumLoanAmount: 0,
      SBASevenMaxLTVPercent: 0,
      SBASevenMinDCR: 0
    },
    SBAFiveFourLoans: {
      SBAFiveFourFirstDeedRealEstate: "UNKNOWN",
      SBAFiveFourFirstDeedRealEquipment: "UNKNOWN",
      SBAFiveFourRefinanceProgram: "UNKNOWN",
      SBAFiveFourFirstDeedRealEstateBridge: "UNKNOWN",
      SBAFiveFourFirstDeedEquipmentBridge: "UNKNOWN",
      SBAFiveFourRefinanceBridge: "UNKNOWN",
      SBAFiveFourMinumumLoanAmount: 0,
      SBAFiveFourMaximumLoanAmount: 0,
      SBAFiveFourMaxLTVPercent: 0,
      SBAFiveFourMinDCR: 0
    },
    construction: {
      investment: "UNKNOWN",
      renovation: "UNKNOWN",
      residentialLongterm: "UNKNOWN",
      residentialFixandFlip: "UNKNOWN",
      groundUpSpecHome: "UNKNOWN",
      ownerUser: "UNKNOWN",
      tractHomes: "UNKNOWN",
      apartments: "UNKNOWN",
      constructiontoPermanent: "UNKNOWN",
      landDevelopment: "UNKNOWN",
      residential: "UNKNOWN",
      PUD: "UNKNOWN",
      purchaseWithLand: "UNKNOWN",
      entitlements: "UNKNOWN",
      miniperm: "UNKNOWN",
      leasedLand: "UNKNOWN",
      brokenProject: "UNKNOWN",
      manufacturedHomeSingleWide: "UNKNOWN",
      manufacturedHomeDoubleWide: "UNKNOWN",
      constructionMinumumLoanAmount: 0,
      constructionMaximumLoanAmount: 0,
      constructionMaxLTVPercent: 0,
      constructionMaxLTCPercent: 0,
      constructionNonSBAMaxARV: 0,
      constructionMinDCR: 0
    },
    businessLendingNonSBA: {
      businessCreditCard: "UNKNOWN",
      businessExpansionnoRE: "UNKNOWN",
      equipmentFinancing: "UNKNOWN",
      businessAcquisitionsMergers: "UNKNOWN",
      franchisePurchases: "UNKNOWN",
      revolvingBLOCFirstPosition: "UNKNOWN",
      revolvingBLOCSecondPosition: "UNKNOWN",
      accountsReceivable: "UNKNOWN",
      crossCollateral: "UNKNOWN",
      equipment: "UNKNOWN",
      invoiceFinancing: "UNKNOWN",
      irrevocableTrust: "UNKNOWN",
      projectionBased: "UNKNOWN",
      purchaseOrderFinancing: "UNKNOWN",
      realEstate: "UNKNOWN",
      stockSavings: "UNKNOWN",
      businessLendingMinumumLoanAmount: 0,
      businessLendingMaximumLoanAmount: 0,
      businessLendingMaxLTVPercent: 0,
      businessLendingMinDCR: 0
    },
    nonCommercialResidentialLending: {
      conventionalFNMA: "UNKNOWN",
      governmentFHA: "UNKNOWN",
      kRehab: "UNKNOWN",
      portfolio: "UNKNOWN",
      jumbo: "UNKNOWN"
    },
    privateMoneyLending: {
      privateMoneyMinumumLoanAmount: 0,
      privateMoneyMaximumLoanAmount: 0,
      privateMoneyMaxLTVPercentCommercial: 0,
      privateMoneyMaxLTVPercentResidential: 0,
      privateMoneyMaxARVCommercial: 0,
      privateMoneyMaxARVResidential: 0,
      privateMoneyMinimumDCR: 0,
      privateMoneyFixedRateAmortized: "UNKNOWN",
      privateMoneyAdjustableRateAmortized: "UNKNOWN",
      privateMoneyinterestOnly: "UNKNOWN",
      privateMoneyInterestRateMin: 0,
      privateMoneyInterestRateMax: 0,
      privateMoneyTermRangeMax: 0,
      privateMoneyTermRangeMin: 0,
      privateMoneyFeesFlatMin: 0,
      privateMoneyFeesFlatMax: 0,
      privateMoneyFeesPointsMin: 0,
      privateMoneyFeesPointsMax: 0,
      privateClosingCostsMin: 0,
      privateClosingCostsMax: 0,
      privateDaysToFundingMin: 0,
      privateDaysToFundingMax: 0
    },
    multiUnitLiving: {
      multiUnitFraternitySorority: "UNKNOWN",
      multiUnitMultiFamily: "UNKNOWN",
      multiUnitStudentHousing: "UNKNOWN",
      multiUnitHotelMotelFlag: "UNKNOWN",
      multiUnitMobileHomePark: "UNKNOWN",
      multiUnitCondoTownHome: "UNKNOWN",
      multiUnitHotelMotelNoFlag: "UNKNOWN",
      multiUnitAssisstedLiving: "UNKNOWN"
    },
    automotive: {
      automotiveBodyShop: "UNKNOWN",
      automotiveDealerShip: "UNKNOWN",
      automotiveCarWash: "UNKNOWN",
      automotiveGasStation: "UNKNOWN"
    },
    healthcare: {
      healthcareDoctorsOffice: "UNKNOWN",
      healthcareHospital: "UNKNOWN",
      healthcareMedicalLab: "UNKNOWN"
    },
    retail: {
      retailRestaurant: "UNKNOWN",
      retailMall: "UNKNOWN",
      retailSingleTenant: "UNKNOWN"
    },
    miscellaneous: {
      miscellaneousChurchReligion: "UNKNOWN",
      miscellaneousIndustrialWarehouse: "UNKNOWN",
      miscellaneousOffice: "UNKNOWN",
      miscellaneousEntertainment: "UNKNOWN",
      miscellaneousMaritimeMarina: "UNKNOWN",
      miscellaneousRawLand: "UNKNOWN",
      miscellaneousFarmAgriculture: "UNKNOWN",
      miscellaneousMixedUse: "UNKNOWN",
      miscellaneousStorage: "UNKNOWN",
      miscellaneousLeaseholdProperty: "UNKNOWN"
    },
    financialCreditIssue: {
      financialCreditIssueBankruptcy: "UNKNOWN",
      financialCreditIssueNonUSCitizen: "UNKNOWN",
      financialCreditIssueMissedPayments: "UNKNOWN",
      financialCreditIssueForeclosure: "UNKNOWN",
      financialCreditIssueShortSale: "UNKNOWN",
      financialCreditIssueTaxLiens: "UNKNOWN",
      financialCreditIssueLowFICO: "UNKNOWN",
      financialCreditIssueLowLiquidity: "UNKNOWN",
      financialCreditIssueJudgements: "UNKNOWN"
    },
    miscellaneousQualifiers: {
      miscellaneousQualifiersExchange: "UNKNOWN",
      miscellaneousQualifiersNonProfit: "UNKNOWN",
      miscellaneousQualifiersNonRecourse: "UNKNOWN",
      miscellaneousQualifiersFactoring: "UNKNOWN",
      miscellaneousQualifiersCannabisRelated: "UNKNOWN",
      miscellaneousQualifiersStartUp: "UNKNOWN",
      miscellaneousQualifiersAssestBasedLending: "UNKNOWN",
      miscellaneousQualifiersResidentialBridge: "UNKNOWN",
      miscellaneousQualifiersInterestOnlyIndefinite: "UNKNOWN",
      miscellaneousQualifiersInterestOnlyIntoTerm: "UNKNOWN",
      miscellaneousQualifiersRelationshipPricing: "UNKNOWN",
      miscellaneousQualifiersRequiredDepositRelationship: "UNKNOWN",
      miscellaneousQualifiersFirstLienPosition: "UNKNOWN",
      miscellaneousQualifiersSecondLientPosition: "UNKNOWN",
      miscellaneousQualifiersSubordinateFinancing: "UNKNOWN"
    },
    avatar: "/static/images/profile-image.jpg",
    following: [],
    followers: [],
    username: "ericaltshuler",
    email: "ericaltshuler66@gmail.com",
    password: "$2b$10$iww3IQYr7aGyxGXtG0fNWusor5fB5/WUHi2dZqH94B0sEWIv.sB0m"
  }
];

exports.formatAllUsers = arr => {
  const usersArr = [];

  arr.forEach(ele => {
    // if (ele.hasOwnProperty("_doc")) {
    const flatUser = ele["_doc"];
    const nestedUserObj = {};

    const inner = obj => {
      for (let key in obj) {
        if (obj.hasOwnProperty(key)) {
          if (typeof obj[key] === "object") {
            inner(obj[key]);
          }
          if (
            typeof obj[key] !== "object" &&
            key !== "0" &&
            key !== "1" &&
            key !== "2" &&
            key !== "3" &&
            key !== "4" &&
            key !== "5" &&
            key !== "6" &&
            key !== "7" &&
            key !== "8" &&
            key !== "9" &&
            key !== "10" &&
            key !== "11" &&
            key !== "12" &&
            key !== "password" && 
            key !== "avatar" &&
            key !=="_bsontype"
          ) {
            nestedUserObj[key] = obj[key];
          }
        }
      }
    };
    inner(flatUser);
    usersArr.push(nestedUserObj);
    // }
  });
  console.log(usersArr);

  return usersArr;
};
