const listOfLenderTypes = [
  { value: "ownerOccupied.purchase", label: "Owner Occupied - Purchase" },
  { value: "ownerOccupied.refinance", label: "Owner Occupied - Refinance" },
  { value: "ownerOccupied.cashOutRefinance", label: "Owner Occupied - Cash Out Refinance" },
  { value: "ownerOccupied.renovationImprovement", label: "Owner Occupied - Renovation Improvement" },
  { value: "ownerOccupied.bridge", label: "Owner Occupied - Bridge" },
  { value: "ownerOccupied.revolvingBusinessLOC1stPosition", label: "Owner Occupied - Revolving Business LOC 1st Position" },
  { value: "ownerOccupied.revolvingBusinessLOC2stPosition", label: "Owner Occupied - Revolving LOC 2nd Position" },
  { value: "investmentNonSBARealEstate.investmentPurchase", label: "Investment Non SBA Real Estate - Purchase" },
  { value: "investmentNonSBARealEstate.investmentRefinance", label: "Investment Non SBA Real Estate - Refinance" },
  { value: "investmentNonSBARealEstate.investmentCashOutRefinance", label: "Investment Non SBA Real Estate - Cash Out Refinance" },
  { value: "investmentNonSBARealEstate.investmentRenovationImprovement", label: "Investment Non SBA Real Estate - Renovation Improvement" },
  { value: "investmentNonSBARealEstate.investmentBridge", label: "Investment Non SBA Real Estate -  Bridge" },
  { value: "investmentNonSBARealEstate.investmentRevolvingBusinessLOC1stPosition", label: "Investment Non SBA Real Estate -  Revolving Business LOC 1st Position" },
  { value: "investmentNonSBARealEstate.investmentRevolvingBusinessLOC2stPosition", label: "Investment Non SBA Real Estate -  Revolving Business LOC 2nd Position" },
  { value: "sbaSevenALoans.sbaExpress", label: "SBA 7A - SBA Express" },
  { value: "sbaSevenALoans.exoprtExpressWC", label: "SBA 7A - Export Express WC" },
  { value: "sbaSevenALoans.internationalTrade", label: "SBA 7A - International Trade" },
  { value: "sbaSevenALoans.seasonalCAPLines", label: "SBA 7A - Seaonal CAP Lines" },
  { value: "sbaSevenALoans.ownerOccupiedCommercial", label: "SBA 7A - Owner Occupied Commercial" },
  { value: "sbaSevenALoans.debtRefinance", label: "SBA 7A -  Debt Refinance" },
  { value: "sbaSevenALoans.contractCAPLines", label: "SBA 7A Loans - Contract CAP Lines" },
  { value: "sbaSevenALoans.buildersCAPLines", label: "SBA 7A - Builders CAP Lines" },
  { value: "sbaSevenALoans.workingCAPLines", label: "SBA 7A - Working CAP Lines" },
  { value: "sbaSevenALoans.sbaMicroLoan", label: "SBA 7A - SBA Micro Loan" },
  { value: "sbaSevenALoans.businessAcquisition", label: "SBA 7A -  Business Acquisition" },
  { value: "SBAFiveFourLoans.SBAFiveFourFirstDeedEquipmentBridge", label: "SBA 54 Loans - First Deed Equipment Bridge" },
  { value: "SBAFiveFourLoans.SBAFiveFourFirstDeedRealEquipment", label: "SBA 54 Loans - First Deed Real Equipment" },
  { value: "SBAFiveFourLoans.SBAFiveFourFirstDeedRealEstate", label: "SBA 54 Loans - First Deed Real Estate" },
  { value: "SBAFiveFourLoans.SBAFiveFourFirstDeedRealEstateBridge", label: "SBA 54 Loans - First Deed Real Estate Bridge" },
  { value: "SBAFiveFourLoans.SBAFiveFourRefinanceBridge", label: "SBA 54 Loans - Refinance Bridge" },
  { value: "SBAFiveFourLoans.SBAFiveFourRefinanceProgram", label: "SBA 54 Loans - Refinance Program" },
  { value: "construction.investment", label: "Construction - Investment" },
  { value: "construction.renovation", label: "Construction - Renovation" },
  { value: "construction.residentialLongterm", label: "Construction - Residential Long Term" },
  { value: "construction.residentialFixandFlip", label: "Construction - Residential Fix and Flip" },
  { value: "construction.groundUpSpecHome", label: "Construction - Ground Up Spec Home" },
  { value: "construction.ownerUser", label: "Construction - Owner User" },
  { value: "construction.tractHomes", label: "Construction - Tract Homes" },
  { value: "construction.apartments", label: "Construction - Apartments" },
  { value: "construction.constructiontoPermanent", label: "Construction - Constructoin to Permanent" },
  { value: "construction.landDevelopment", label: "Construction - Land Developement" },
  { value: "construction.residential", label: "Construction - Residential" },
  { value: "construction.PUD", label: "Construction - PUD" },
  { value: "construction.purchaseWithLand", label: "Construction - Purchase with Land" },
  { value: "construction.entitlements", label: "Construction - Entitlements" },
  { value: "construction.miniperm", label: "Construction - Mini Permit" },
  { value: "construction.leasedLand", label: "Construction - Leased Land" },
  { value: "construction.brokenProject", label: "Construction - Broken Project" },
  { value: "construction.apartments", label: "Construction - Apartments" },
  { value: "construction.manufacturedHomeSingleWide", label: "Construction - Manufactured Home Single Wide" },
  { value: "construction.manufacturedHomeDoubleWide", label: "Construction -  Manufactured Home Double Wide" },
  { value: "businessLendingNonSBA.businessCreditCard", label: "Busniess Lending Non SBA - Business Credit Card" },
  { value: "businessLendingNonSBA.businessExpansionnoRE", label: "Busniess Lending Non SBA - Business Expansion No RE" },
  { value: "businessLendingNonSBA.equipmentFinancing", label: "Busniess Lending Non SBA - Equipment Financing" },
  { value: "businessLendingNonSBA.businessAcquisitionsMergers", label: "Busniess Lending Non SBA - Business Acquisitions Mergers" },
  { value: "businessLendingNonSBA.franchisePurchases", label: "Busniess Lending Non SBA - Franchise Purchases" },
  { value: "businessLendingNonSBA.revolvingBLOCFirstPosition", label: "Busniess Lending Non SBA -  Revolving BLOC 1st Position" },
  { value: "businessLendingNonSBA.revolvingBLOCSecondPosition", label: "Busniess Lending Non SBA - Revolving BLOC 2nd Position" },
  { value: "businessLendingNonSBA.accountsReceivable", label: "Busniess Lending Non SBA - Accounts Receivable" },
  { value: "businessLendingNonSBA.crossCollateral", label: "Busniess Lending Non SBA - Cross Collateral" },
  { value: "businessLendingNonSBA.equipment", label: "Busniess Lending Non SBA - Equipment" },
  { value: "businessLendingNonSBA.invoiceFinancing", label: "Busniess Lending Non SBA - Invoise Financing" },
  { value: "businessLendingNonSBA.irrevocableTrust", label: "Busniess Lending Non SBA - Irrevocable Trust" },
  { value: "businessLendingNonSBA.projectionBased", label: "Busniess Lending Non SBA - Projection Based" },
  { value: "businessLendingNonSBA.purchaseOrderFinancing", label: "Busniess Lending Non SBA - Purchase Order Financing" },
  { value: "businessLendingNonSBA.realEstate", label: "Busniess Lending Non SBA - Real Estate" },
  { value: "businessLendingNonSBA.stockSavings", label: "Busniess Lending Non SBA - Stock Savings" },
  { value: "nonCommercialResidentialLending.conventionalFNMA", label: "Non Commercial Residential Lending - Conventional FNMA" },
  { value: "nonCommercialResidentialLending.governmentFHA", label: "Non Commercial Residential Lending - Government FHA" },
  { value: "nonCommercialResidentialLending.kRehab", label: "Non Commercial Residential Lending - K Rehab" },
  { value: "nonCommercialResidentialLending.portfolio", label: "Non Commercial Residential Lending - Portfolio" },
  { value: "nonCommercialResidentialLending.jumbo", label: "Non Commercial Residential Lending - Jumbo" },
  { value: "privateMoneyLending.privateMoneyAdjustableRateAmortized", label: "Private Money Lending - Private Money Adjustable Rate Amortized" },
  { value: "privateMoneyLending.privateMoneyinterestOnly", label: "Private Money Lending - Private Money Fixed Rate Amortized" },
  { value: "privateMoneyLending.privateMoneyFixedRateAmortized", label: "Private Money Lending - Private Money Interest Only" },
  { value: "multiUnitLiving.multiUnitAssisstedLiving", label: "Multi-Unit Living - Assisted Living" },
  { value: "multiUnitLiving.multiUnitCondoTownHome", label: "Multi-Unit Living - Condo Town Home" },
  { value: "multiUnitLiving.multiUnitFraternitySorority", label: "Multi-Unit Living - Fraternity/Sorority" },
  { value: "multiUnitLiving.multiUnitHotelMotelFlag", label: "Multi-Unit Living - Hotel/Motel Flag" },
  { value: "multiUnitLiving.multiUnitHotelMotelNoFlag", label: "Multi-Unit Living - Hotel/Motel No Flag" },
  { value: "multiUnitLiving.multiUnitMobileHomePark", label: "Multi-Unit Living - Mobile Home Park" },
  { value: "multiUnitLiving.multiUnitMultiFamily", label: "Multi-Unit Living - Multi Family" },
  { value: "multiUnitLiving.multiUnitStudentHousing", label: "Multi-Unit Living - Student Housing" },
  { value: "automotive.automotiveBodyShop", label: "Automotive - Body Shop" },
  { value: "automotive.automotiveCarWash", label: "Automotive - Car Wasg" },
  { value: "automotive.automotiveDealerShip", label: "Automotive - Dealership" },
  { value: "automotive.automotiveGasStation", label: "Automotive - Gas Station" },
  { value: "healthcare.healthcareDoctorsOffice", label: "Healthcare - Doctor's Office" },
  { value: "healthcare.healthcareHospital", label: "HealthCare - Hospital" },
  { value: "healthcare.healthcareMedicalLab", label: "HealthCare - Medical Lab" },
  { value: "retail.retailRestaurant", label: "Retail - Restaurant" },
  { value: "retail.retailMail", label: "Retail - Mail" },
  { value: "retail.retailSingleTenant", label: "Retail - Single Tenant" },
  { value: "miscellaneous.miscellaneousChurchReligion", label: "Miscellaneous - Church/Religion" },
  { value: "miscellaneous.miscellaneousEntertainment", label: "Miscellaneous - Entertainement" },
  { value: "miscellaneous.miscellaneousFarmAgriculture", label: "Miscellaneous - Farm/Agriculture" },
  { value: "miscellaneous.miscellaneousIndustrialWarehouse", label: "Miscellaneous - Industrial Warehouse" },
  { value: "miscellaneous.miscellaneousLeaseholdProperty", label: "Miscellaneous - Leasehold Property" },
  { value: "miscellaneous.miscellaneousMaritimeMarina", label: "Miscellaneous - Maritime Marina" },
  { value: "miscellaneous.miscellaneousMixedUse", label: "Miscellaneous - Mixed Use" },
  { value: "miscellaneous.miscellaneousOffice", label: "Miscellaneous - Office" },
  { value: "miscellaneous.miscellaneousRawLand", label: "Miscellaneous - Raw Land" },
  { value: "miscellaneous.miscellaneousStorage", label: "Miscellaneous - Storage" },
  { value: "financialCreditIssue.financialCreditIssueBankruptcy", label: "Financial Credit Issue - Bankruptcy" },
  { value: "financialCreditIssue.financialCreditIssueForeclosure", label: "Financial Credit Issue - Foreclosure" },
  { value: "financialCreditIssue.financialCreditIssueJudgements", label: "Financial Credit Issue - Judgements" },
  { value: "financialCreditIssue.financialCreditIssueLowFICO", label: "Financial Credit Issue - Low FICO" },
  { value: "financialCreditIssue.financialCreditIssueLowLiquidity", label: "Financial Credit Issue - Low Liquidity" },
  { value: "financialCreditIssue.financialCreditIssueMissedPayments", label: "Financial Credit Issue - Missed Payments" },
  { value: "financialCreditIssue.financialCreditIssueNonUSCitizen", label: "Financial Credit Issue - Non-US Citizen" },
  { value: "financialCreditIssue.financialCreditIssueShortSale", label: "Financial Credit Issue - Short Sale" },
  { value: "financialCreditIssue.financialCreditIssueTaxLiens", label: "Financial Credit Issue - Tax Liens" },
  { value: "miscellaneousQualifiers.miscellaneousQualifiersAssestBasedLending", label: "Miscellaneous Qualifiers - Assests Based Lending" },
  { value: "miscellaneousQualifiers.miscellaneousQualifiersCannabisRelated", label: "Miscellaneous Qualifiers - Cannabis Related" },
  { value: "miscellaneousQualifiers.miscellaneousQualifiersExchange", label: "Miscellaneous Qualifiers - Exchange" },
  { value: "miscellaneousQualifiers.miscellaneousQualifiersFactoring", label: "Miscellaneous Qualifiers - Factoring" },
  { value: "miscellaneousQualifiers.miscellaneousQualifiersFirstLienPosition", label: "Miscellaneous Qualifiers - First Lien Positions" },
  { value: "miscellaneousQualifiers.miscellaneousQualifiersInterestOnlyIndefinite", label: "Miscellaneous Qualifiers - Interest Only Indefinite" },
  { value: "miscellaneousQualifiers.miscellaneousQualifiersInterestOnlyIntoTerm", label: "Miscellaneous Qualifiers - Interest only Into Term" },
  { value: "miscellaneousQualifiers.miscellaneousQualifiersNonProfit", label: "Miscellaneous Qualifiers - Nonprofit" },
  { value: "miscellaneousQualifiers.miscellaneousQualifiersNonRecourse", label: "Miscellaneous Qualifiers - Non-recourse" },
  { value: "miscellaneousQualifiers.miscellaneousQualifiersRelationshipPricing", label: "Miscellaneous Qualifiers - Relationship Pricing" },
  { value: "miscellaneousQualifiers.miscellaneousQualifiersRequiredDepositRelationship", label: "Miscellaneous Qualifiers - Required Deposit Relationship" },
  { value: "miscellaneousQualifiers.miscellaneousQualifiersResidentialBridge", label: "Miscellaneous Qualifiers - Residential Bridge" },
  { value: "miscellaneousQualifiers.miscellaneousQualifiersSecondLientPosition", label: "Miscellaneous Qualifiers - Second Lient Position" },
  { value: "miscellaneousQualifiers.miscellaneousQualifiersStartUp", label: "Miscellaneous Qualifiers - Startup" },
  { value: "miscellaneousQualifiers.miscellaneousQualifiersSubordinateFinancing", label: "Miscellaneous Qualifiers - Subordinate Financing" }
];


export default listOfLenderTypes;